apiVersion: v1
kind: Secret
metadata:
  name: ${DATABASE_SERVICE_NAME}
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
stringData:
  database-password: ${REDIS_PASSWORD}
