apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-to-redis-cluster-admin
subjects:
  - kind: ServiceAccount
    name: redis-cluster-admin
roleRef:
  kind: ClusterRole
  name: admin
