apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: redis-6-cluster
message: |-
  The following service(s) have been created in your project: ${DATABASE_SERVICE_NAME}.

         Password: ${REDIS_PASSWORD}
   Connection URL: redis://${DATABASE_SERVICE_NAME}:6379/

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/redis-container/blob/master/5.
metadata:
  annotations:
    description: |-
      Redis in-memory data structure store, without persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/redis-container/blob/master/5.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    iconClass: icon-redis
    openshift.io/display-name: Redis 6 Cluster
    openshift.io/documentation-url: https://github.com/sclorg/redis-container/tree/master/6
    openshift.io/long-description: This template provides a Redis 6 cluster using StatefulSets for both master and slave.  The data is stored on persistent storage.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    samples.operator.openshift.io/version: 4.7.8
    tags: database,redis
  labels:
    samples.operator.openshift.io/managed: "false"
  name: redis-6-cluster
  namespace: openshift
parameters:
  - description: Maximum amount of memory the container can use.
    displayName: Memory Limit
    name: MEMORY_LIMIT
    required: true
    value: 512Mi
  - description: PersistentVolumeClaim size
    displayName: Storage Size
    name: PERSISTENT_SIZE
    required: true
    value: 1Gi
  - description: Number of nodes
    displayName: Cluster nodes number
    name: CLUSTER_SIZE
    value: '3'
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: NAMESPACE
    value: openshift
  - description: The name of the OpenShift Service exposed for the database.
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: redis
  - description: Password for the Redis connection user.
    displayName: Redis Connection Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: REDIS_PASSWORD
    required: true
  - description: Version of Redis image to be used (1, 1-7 or latest).
    displayName: Version of Redis Image
    name: REDIS_VERSION
    required: true
    value: 1-7
